name: UrbanTide
favicon: null
layout_spectrum: 0.8867901214398444
typography_spectrum: 0.8043796380516142
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9821523337159306
  lightness: 0.33561307145282626
  saturation: 0.17078522476367652
  rhythmicContrast: 0.19023979804478586
purpose: []
